// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewVideo struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	UserID      string `json:"userId"`
	URL         string `json:"url"`
}

type User struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

type Video struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	Description string   `json:"description"`
	URL         string   `json:"url"`
	CreatedAt   string   `json:"createdAt"`
	Related     []*Video `json:"related"`
}

